### ISSUE TITLE
백엔드 배열 데이터 → 프론트엔드 UI로 불러오는 방법

### ISSUE THREAD

**Issue by ssook1222** [ssook1222/TMeet#41]
#39 
@eastflag 
안녕하세요, **참가자 거리 계산하는 화면 UI를 짜고 백엔드와 연동**하던 중 막힌 부분이 있어 여쭤보고자 합니다🥲        
     
<img width="425" alt="스크린샷 2022-07-25 오후 1 50 09" src="https://user-images.githubusercontent.com/60427387/180700840-1c34799a-a316-474e-8953-e8b33666b517.png">

----

먼저 간단하게 상황을 적자면,      
**사용자가 닉네임을 누르고 search 버튼을 누르면, 프론트엔드에서는 사용자가 입력한 닉네임을 request body에 넣어 백엔드로** 보냅니다.      
**백엔드에서는** 프론트엔드가 보낸 값을 기반으로 사용자 근처의 지하철역, 이메일 등 **회원가입 시 입력한 개인정보를** 아래와 같은 형태로 **프론트엔드로 보냅니다.**   
      
<img width="547" alt="스크린샷 2022-07-25 오후 1 54 10" src="https://user-images.githubusercontent.com/60427387/180701228-9e33e2f5-9c12-4f8c-b387-8092fac67a1e.png">

---

제가 여쭤보고자 하는 부분은 

> **엔드유저에게 위의 데이터 형태 중 닉네임만 추출하여 UI 단에 보여주고자 합니다.**    
다만, 백엔드에서 보낸 response를 array로 받아 이를 출력하면 프론트엔드 콘솔에서는 잘 가져오는데 화면 단에 그리려고만 하면 undefined가 뜨는 상황입니다.    
**타입스크립트를 쓰지 않는 현재 상황**에서 괜찮은 방법이 있을까요?
    
아래는 프론트엔드 단에서 백엔드 api를 호출하여 array에 저장하는 코드입니다.
```javascript
let user=[]

    useEffect(() => {
        getUser();
    }, []);

    const getUser = async () => {
        const res  = await axios.post('/api/nickname', "쑥");
        user.push(res.data)
    }
```
      
아래는 위에서 저장한 배열을 데이터 바인딩을 이용하여 칩 형태로 UI 단에 출력하고자 한 코드입니다.
```javascript
                  <Grid
                        style={{marginLeft:"30px", marginRight:"10px", padding:"10px"}}
                        container spacing={{ xs: 1, md: 2 }} columns={{ xs: 6, sm:16, md: 16 }}>
                        {Array.from(Array(user.length+1)).map((_, index) => (
                            <Grid item xs={2} sm={4} md={4} key={index}>
                                <Chip
                                    label={user[index].nickname}
                                    variant="filled"
                                    onDelete={handleDelete}  />
                            </Grid>
                        ))}
                    </Grid>
```

      
이 경우 위의 getUser에서는 user array의 데이터가 콘솔에 잘 찍히는데, 아래의 user array에서는 undefined가 나옵니다.    
[멘토님의 블로그](https://eastflag.co.kr/fullstack/react-bootstrap-typescript/react-board-view/) 역시 참고했지만,   
아래와 같이 useState에 있어 Boolean을 그런 형태로 사용할 수 없다는 에러가 떴습니다.

   
<img width="773" alt="스크린샷 2022-07-25 오후 2 03 50" src="https://user-images.githubusercontent.com/60427387/180702279-cf7db100-0d89-408e-ad72-b327064ada4a.png">

**Comment by eastflag** [comment]
user를 state로 관리해야하는데 왜 변수로 받은거지.
user를 state로 선언하고 user 배열을 변경할때 immutable해야 하므로 push 같은거 쓰면 안되고 immputable한 함수를 사용해야 함.

**Comment by ssook1222** [comment]
@eastflag 
<img width="440" alt="스크린샷 2022-08-05 오후 3 35 01" src="https://user-images.githubusercontent.com/60427387/183016428-75f43c8b-88ed-42e8-9959-f7125d07a336.png">
알려주신대로 진행했더니 해결되었습니다!!!     
감사합니다 : )
