### ISSUE TITLE
Naver Map API Error

### ISSUE THREAD

**Issue by ssook1222** [ssook1222/TMeet#54]
#50 

@eastflag 
안녕하세요 멘토님!
멘토님이 카톡으로 보내주셨던 오류(하단 이미지 참조) 관련해서 직접 해결해보려고 했는데,    
<img width="1229" alt="스크린샷 2022-08-16 오후 1 04 46" src="https://user-images.githubusercontent.com/60427387/184795639-694ad8cc-28f2-433e-91bb-501ab59f029c.png">

잘 해결되지 않아서요...   
지도 세팅 하는 것에 있어서 로드 순서가 잘 못 된 거 같은데 제가 제대로 파악하고 있는 게 맞는지,      
잘못 파악했다면 어떤 식으로 진행하는 것이 맞는지 조언해 주실 수 있으실까요?

확인해주셔서 감사합니다☺️  

---

브랜치는 `feature/place`입니다!

**Comment by eastflag** [comment]
위도 경도 부분 잘못됏어

2022년 8월 16일 (화) 오후 1:08, ssook ***@***.***>님이 작성:

**Comment by ssook1222** [comment]
헉 동일한 걸 두 번 사용하고 있었네요 감사합니다!! 바로 해결했습니다.
