### ISSUE TITLE
Object(=Json Array) Mapping 관련 질문 드립니다! 

### ISSUE THREAD

**Issue by ssook1222** [ssook1222/TMeet#56]
@eastflag 

#55 (Issue 깃허브 브랜치 : feature/place)

안녕하세요, 멘토님!     
백엔드에서 **아래와 같은 데이터**를 보내고 있는데, 프론트엔드에서 해당 데이터를 어떻게 바인딩 해야 될 지 조언을 듣고 싶어 남깁니다.    
<img width="1175" alt="스크린샷 2022-08-21 오후 11 29 52" src="https://user-images.githubusercontent.com/60427387/185795986-16328267-ff67-4d7f-a18a-534aade964ea.png">

아래는 데이터 바인딩을 시도한 코드입니다.   

```javascript
const [searchList, setSearchList] = useState<Array<Search>>([]);
useEffect(() => {
        getSearchList();
    }, []);
const SearchList: React.FC = () => {
    return (
        <div>
            {
                searchList.map((search : Search)=>{
                    {search.title}
                })
            }
        </div>
    );
```

그랬더니 아래와 같은 오류 메시지가 뜹니다. 

<img width="1197" alt="스크린샷 2022-08-21 오후 10 04 02" src="https://user-images.githubusercontent.com/60427387/185796140-8deaa787-f2aa-4e7a-82f9-e798cb23e355.png">

찾아보니 Object에서는 map을 사용할 수 없다고 하여, IsArray로 확인해보니   
처음 선언 시에는 Search type data가 들어가는 Array였지만, 백엔드에서 데이터를 받아오자마자 Object가 됩니다.   
(아래 이미지는 isArray가 false인 모습)

<img width="1198" alt="스크린샷 2022-08-21 오후 10 03 20" src="https://user-images.githubusercontent.com/60427387/185796262-cdd87f35-6845-45c3-b152-1f1ebd616e8f.png">

제가 놓친 부분이나 조언하실 점 알려주시면 감사하겠습니다!

**Comment by eastflag** [comment]
소스 위치가 어디니?
저것만 봐서는 잘 모르겠지만,,,
data가 배열이니까 그걸 searchList 에 넣어면 될거 같은데,

2022년 8월 21일 (일) 오후 11:37, ssook ***@***.***>님이 작성:

**Comment by ssook1222** [comment]
@eastflag 
소스 코드 위치는 `tmeet-frontend/src/pages/place/SearchList.tsx`입니다!    
지금 코드 상태는 이런데, 이렇게 하면 searchList.map이 function이 아니라고 떠서 흰 화면만 뜨는 중입니다!

```javascript
const SearchList: React.FC = () => {
    const [searchList, setSearchList] = useState<Array<Search>>([]);

    useEffect(() => {
        getSearchList();
    }, []);

    const getSearchList = async () => {
        // res는 http response의 header + body를 모두 갖고 있다.
        const res  = await axios.get('/api/search-subway/서울지방병무청');
        setSearchList(res.data);
    }

    console.log(searchList)

    return (
        <div>
            {
                searchList.map((search : Search)=>{
                    {search.title}
                })
            }
        </div>
    );
};

export default SearchList;
```

**Comment by eastflag** [comment]
res.data 는 response body이고 로그 찍은거 보면 이게 객체이고
그 안에 또 data  가 있으니까,
res.data.data 로 해야 할거 같은데,

2022년 8월 22일 (월) 오후 1:18, ssook ***@***.***>님이 작성:

**Comment by ssook1222** [comment]
<img width="464" alt="스크린샷 2022-08-23 오전 9 15 10" src="https://user-images.githubusercontent.com/60427387/186041518-634a3bc6-754d-4fd3-b07f-42c0b8ca74c0.png">

해결했습니다! 감사합니다 :)
