### ISSUE TITLE
아이콘이 [object Object]로 뜨는 에러 관련 질문 드립니다.

### ISSUE THREAD

**Issue by onebbu** [ssook1222/TMeet#60]
날씨 아이콘을 MUI 아이콘을 통해 구현하려하는 도중 결과 화면이 다음과 같이 되어 질문드립니다.
![image](https://user-images.githubusercontent.com/101400455/186070971-aa753f42-8fc0-464a-9189-d0dcd8d7d888.png)

우선,
`weatherIcon.innerHTML = <span className="material-icons"> wb_sunny </span>;`
위와 같이 아이콘을 innerHTML을 사용해 입력하려 했으나 [object Object]로 뜨는 상황입니다.
이를 해결하기 위해 찾아봤으나 제가 해결하기 어려워 질문드립니다.

추가로,
찾아보니 innerHTML을 사용해 아이콘을 입력하는 다른 방법으로 fontAwesome 아이콘이 있는데,
mui아이콘을 사용해서 구현해야할지 fontAwesome 아이콘을 사용해 구현해야할지 판단이 되지 않는 상황입니다.
어떤 방법을 사용해서 구현해야할지 질문드립니다.

---------------------------------------------------------------------------------------------------------------------------------------------------
아래는 findWeather함수 전체 코드 첨부드립니다.

    //백엔드에서 가져온 데이터에서 날씨 찾는 기능
    function findWeather() {
        weatherLst2 = weatherLst1.flat();
        let resultId = document.getElementById('weather');
        let parent = resultId.parentElement;
        for (let i = 0; parent.childElementCount <=weatherLst2.length; i++) {

            //  모임날짜
            let weatherDate = document.createElement('div');
            weatherDate.innerHTML = weatherLst2[i].date;
            parent.appendChild(weatherDate);

           // 날씨 아이콘 삽입
            let weatherIcon = document.createElement('span');
            **weatherIcon.innerHTML = <span className="material-icons"> wb_sunny </span>; <-질문 드린 부분**
            parent.appendChild(weatherIcon);
        }
    }

        return (
        <div style={{display: "flex"}}>
            <div id="weather" onLoad={findWeather}></div>
        </div>
    );

**Comment by ssook1222** [comment]
@eastflag 
![스크린샷 2022-08-27 오후 7 06 57](https://user-images.githubusercontent.com/60427387/187025713-64d13946-1f7c-41af-943e-094a3270ea3a.png)
UseEffect와 조건부 렌더링 사용해서 날씨 아이콘 부분 구현 완료했습니다!

**Comment by eastflag** [comment]
허헉!
일단,,,
이게 어디 들어가는 코드인지 모르겠는데,
프런트는 리액트로 코딩하고 있지 않나? 지금 코드는 리액트 코드가 아니고 그냥 DOM api인데, 어떻게 된거지,,,
브랜치랑 소스 위치를 얘기해줄래,,,

2022년 8월 23일 (화) 오후 1:54, SangEun123 ***@***.***>님이 작성:
